
DELETE FROM public.quiz_questions
WHERE quiz_type = 'medical'
  AND medical_section IN (
    'cardiology', 'respiratory', 'gastrointestinal', 'endocrinology', 
    'renal', 'ob_gyn', 'oncology', 'dermatology', 'emergency', 'ear_and_eye'
  );

INSERT INTO public.quiz_questions(
  quiz_type,
  medical_section,
  question_text,
  option_a,
  option_b,
  option_c,
  option_d,
  correct_option
) VALUES
  ('medical', 'cardiology', 'Which of the following refers to chest pain caused by reduced blood flow to the heart?', 'Myocarditis', 'Angina pectoris', 'Arrhythmia', 'Endocarditis', 'B'),
  ('medical', 'cardiology', 'The medical term for a heart attack is:', 'CHF', 'MI', 'CAD', 'CVA', 'B'),
  ('medical', 'cardiology', 'Which test records the electrical activity of the heart?', 'MRI', 'Echo', 'ECG/EKG', 'CT scan', 'C'),
  ('medical', 'cardiology', 'Which artery supplies blood to the heart muscle?', 'Femoral artery', 'Coronary artery', 'Carotid artery', 'Aortic arch', 'B'),
  ('medical', 'cardiology', '“Atherosclerosis” refers to:', 'Thickening of lung tissue', 'Hardening of the arteries', 'Kidney failure', 'Liver enlargement', 'B'),
  ('medical', 'cardiology', 'Which procedure opens blocked coronary arteries using a balloon?', 'CABG', 'Angioplasty', 'Pacemaker', 'Cardioversion', 'B'),
  ('medical', 'cardiology', 'CABG stands for:', 'Coronary Artery Bypass Graft', 'Cardiac Artery Broken Gland', 'Coronary Balloon Guide', 'Cardio Arrhythmia Base Gate', 'A'),
  ('medical', 'cardiology', 'A patient with “irregular heartbeat” most likely has:', 'Atherosclerosis', 'Arrhythmia', 'Pericardial effusion', 'MI', 'B'),
  ('medical', 'cardiology', 'Which valve separates the left atrium from the left ventricle?', 'Aortic valve', 'Pulmonic valve', 'Mitral valve', 'Tricuspid valve', 'C'),
  ('medical', 'cardiology', 'Which diagnostic test uses ultrasound to visualize heart movement?', 'Echocardiogram', 'ECG', 'X-ray', 'Stress test', 'A'),
  ('medical', 'cardiology', 'A patient reports: “I feel dizzy and almost faint when I stand up quickly.” This may indicate:', 'Hypertensive crisis', 'Orthostatic hypotension', 'Tachycardia', 'Hyperglycemia', 'B'),
  ('medical', 'cardiology', 'We may need to place a stent to keep the artery open.” A stent is best described as:', 'A medication', 'A surgical stitch', 'A small mesh tube inserted into an artery', 'A heart valve replacement', 'C'),
  ('medical', 'cardiology', '“Atrial fibrillation” is best described as:', 'A blockage in coronary arteries', 'Inflammation of the heart muscle', 'An irregular, often rapid heart rhythm', 'A valve infection', 'C'),
  ('medical', 'cardiology', 'The term “ischemia” means:', 'Complete tissue death', 'Reduced blood flow to tissue', 'Increased oxygen supply', 'Heart enlargement', 'B'),
  ('medical', 'cardiology', 'Congestive heart failure (CHF)” refers to:', 'Sudden cardiac arrest', 'Infection of the heart valves', 'Hardening of arteries', 'The heart’s inability to pump blood effectively', 'D'),
  ('medical', 'cardiology', '“Heart murmur” usually refers to:', 'Abnormal heart sound', 'Irregular heartbeat', 'Blocked artery', 'Heart enlargement', 'A'),
  ('medical', 'cardiology', 'Which condition refers to “narrowing of a heart valve”?', 'Regurgitation', 'Stenosis', 'Prolapse', 'Occlusion', 'B'),
  ('medical', 'cardiology', '“Tachycardia” is defined as:', 'Heart rate below 60 bpm', 'Irregular rhythm', 'Heart rate above 100 bpm', 'Weak pulse', 'C'),
  ('medical', 'cardiology', 'he provider says: “The patient has fluid buildup in the lungs due to heart failure.” This condition is called:', 'Pleural effusion', 'Pulmonary edema', 'Pneumonia', 'Bronchitis', 'B'),
  ('medical', 'cardiology', 'The term “cyanosis” refers to:', 'Blue discoloration due to poor oxygen', 'Yellow skin', 'Red rash', 'Severe swelling', 'A'),
  ('medical', 'cardiology', '“Edema” means:', 'Chest tightness', 'Fluid retention/swelling', 'Fainting', 'Excess sweating', 'B'),
  ('medical', 'cardiology', 'A patient says: “I feel like my heart is skipping beats and then racing all of a sudden.” This most likely refers to:', 'Stable angina', 'Heart murmur', 'Cardiac arrest', 'Palpitations', 'D'),
  ('medical', 'cardiology', 'Which chamber of the heart pumps oxygenated blood to the body? Right atrium Right ventricle Left ventricle ✔ Left atrium 24What does “bradycardia” mean?', 'Fast heart rate', 'Irregular heart rhythm', 'Slow heart rate', 'Weak heartbeat', 'C'),
  ('medical', 'cardiology', 'Which of the following medications is used to thin the blood?', 'Insulin', 'Anticoagulants', 'Beta-blockers', 'Steroids', 'B'),
  ('medical', 'respiratory', 'A patient with “shortness of breath” most likely has:', 'Dyspnea', 'Apnea', 'Hemoptysis', 'Cyanosis', 'A'),
  ('medical', 'respiratory', 'Which of the following describes sudden collapse of a lung?', 'Pleural effusion', 'Atelectasis', 'Emphysema', 'Pneumothorax', 'D'),
  ('medical', 'respiratory', 'Which condition is characterized by reversible airway obstruction, wheezing, and shortness of breath?', 'Asthma', 'COPD', 'Pneumonia', 'Tuberculosis', 'A'),
  ('medical', 'respiratory', 'Which imaging test is best for detecting fluid in the lungs?', 'ECG', 'Chest X-ray', 'MRI', 'Ultrasound', 'B'),
  ('medical', 'respiratory', 'Which of the following is a common symptom of COPD?', 'Night sweats', 'Chest pain radiating to arm', 'Chronic cough & shortness of breath', 'Numbness in legs', 'C'),
  ('medical', 'respiratory', 'A patient with sleep apnea experiences:', 'Continuous low oxygen during sleep', 'Coughing up blood', 'Chest tightness only', 'Muscle weakness', 'A'),
  ('medical', 'respiratory', 'Which condition is characterized by progressive destruction of alveoli and difficulty exhaling?', 'Asthma', 'Emphysema', 'Pneumonia', 'Pulmonary edema', 'B'),
  ('medical', 'respiratory', '“Bronchoscopy” is a procedure used to:', 'Check heart valves', 'Visualize airways', 'Measure oxygen', 'Remove fluid from pleura', 'B'),
  ('medical', 'respiratory', 'A patient has a positive Mantoux test. This indicates:', 'Tuberculosis exposure', 'Pneumonia', 'Lung cancer', 'Asthma', 'A'),
  ('medical', 'respiratory', '“Orthopnea” is difficulty breathing when:', 'Sitting', 'Exercising', 'Lying down', 'Standing', 'C'),
  ('medical', 'respiratory', 'Which test measures oxygen saturation in the blood?', 'ECG', 'Pulse oximetry', 'Spirometry', 'Chest X-ray', 'B'),
  ('medical', 'respiratory', '“COPD” stands for:', 'Chronic obstructive pulmonary disease', 'Chronic oxygen pulmonary disorder', 'Cardiac obstructive pulmonary disease', 'Chronic obstructive perfusion defect', 'A'),
  ('medical', 'respiratory', '“Wheezing” is best described as:', 'A crackling sound in the lungs', 'Complete absence of breath sounds', 'A whistling sound during breathing', 'Pain during breathing', 'C'),
  ('medical', 'respiratory', '“Pneumonia” is:', 'Air in the pleural space', 'Infection of the lungs', 'Chronic airway narrowing', 'Fluid around the heart', 'B'),
  ('medical', 'respiratory', 'Which test measures lung function and volume?', 'ECG', 'Echocardiogram', 'Spirometry', 'Blood culture', 'C'),
  ('medical', 'respiratory', 'Which of the following is a symptom of pulmonary embolism?', 'Sudden shortness of breath', 'Gradual cough for months', 'Night sweats', 'Fever only', 'A'),
  ('medical', 'respiratory', '“Bronchodilator” medications are used to:', 'Reduce fluid in lungs', 'Open the airways', 'Treat infection', 'Thin the blood', 'B'),
  ('medical', 'respiratory', '“Intubation” means:', 'Removing fluid from lungs', 'Measuring lung capacity', 'Giving oxygen through a mask', 'Placing a tube into the airway to assist breathing', 'D'),
  ('medical', 'respiratory', '“Hypoxia” refers to:', 'High oxygen levels', 'Low oxygen levels in tissues', 'High carbon dioxide', 'Normal breathing', 'B'),
  ('medical', 'respiratory', 'Which condition refers to “fluid in the lungs”?', 'Pulmonary edema', 'Asthma', 'Bronchitis', 'Pneumothorax', 'A'),
  ('medical', 'respiratory', 'A patient reports coughing up blood. The medical term is:', 'Hemoptysis', 'Hematemesis', 'Epistaxis', 'Hematuria', 'A'),
  ('medical', 'respiratory', 'A patient producing “thick mucus when coughing” is describing:', 'Hemoptysis', 'Sputum', 'Edema', 'Aspiration', 'B'),
  ('medical', 'respiratory', '“Tachypnea” refers to: Slow breathing Painful breathing Rapid breathing ✔ Irregular breathing 24, A patient who “inhales food or liquid into the airway” is experiencing:', 'Aspiration', 'Inhalation therapy', 'Ventilation', 'Perfusion', 'A'),
  ('medical', 'respiratory', '“Ventilator” support is used when:', 'The patient has high blood pressure', 'The patient cannot breathe adequately on their own', 'The patient has a mild cough', 'The patient has chest pain only', 'B'),
  ('medical', 'gastrointestinal', 'A patient with “heartburn” most likely has:', 'Gastritis', 'GERD (acid reflux)', 'Appendicitis', 'Hepatitis', 'B'),
  ('medical', 'gastrointestinal', 'Which procedure uses a camera to examine the upper GI tract?', 'Colonoscopy', 'CT scan', 'Ultrasound', 'Endoscopy (EGD)', 'D'),
  ('medical', 'gastrointestinal', 'Which organ is affected in cholecystitis?', 'Gallbladder', 'Pancreas', 'Liver', 'Appendix', 'A'),
  ('medical', 'gastrointestinal', '“Ascites” refers to:', 'Gas in the stomach', 'Fluid buildup in the abdomen', 'Liver infection', 'Intestinal blockage', 'B'),
  ('medical', 'gastrointestinal', '“Hepatitis” is:', 'Inflammation of the liver', 'Infection of the stomach', 'Colon inflammation', 'Pancreatic failure', 'A'),
  ('medical', 'gastrointestinal', '“Jaundice” refers to:', 'Red skin', 'Swelling of the abdomen', 'Yellowing of the skin and eyes', 'Dark urine only', 'C'),
  ('medical', 'gastrointestinal', '“Dysphagia” refers to:', 'Painful swallowing', 'Difficulty swallowing', 'Vomiting blood', 'Loss of appetite', 'B'),
  ('medical', 'gastrointestinal', '“Proton pump inhibitors (PPIs)” are used to:', 'Treat diarrhea', 'Reduce stomach acid', 'Increase bile production', 'Treat constipation', 'B'),
  ('medical', 'gastrointestinal', '“Laxatives” are medications used to:', 'Stop vomiting', 'Reduce stomach acid', 'Treat liver disease', 'Soften stool and relieve constipation', 'D'),
  ('medical', 'gastrointestinal', '“Nasogastric (NG) tube” is used to:', 'Remove fluid or deliver nutrition to the stomach', 'Measure lung capacity', 'Deliver oxygen', 'Test heart rhythm', 'A'),
  ('medical', 'gastrointestinal', '“Colonic polyp removal” is a procedure done during:', 'Endoscopy', 'Colonoscopy', 'ERCP', 'Gastroscopy', 'B'),
  ('medical', 'gastrointestinal', '“Antacids” are used to:', 'Relieve stomach acid symptoms', 'Increase bile production', 'Stop diarrhea', 'Treat pancreatic inflammation', 'A'),
  ('medical', 'gastrointestinal', '“H. pylori test” is done to:', 'Check colon polyps', 'Measure bile production', 'Test for liver disease', 'Detect bacteria causing stomach ulcers', 'D'),
  ('medical', 'gastrointestinal', '“Endoscopic biopsy” means:', 'Taking tissue samples through an endoscope', 'Removing polyps surgically', 'Measuring stomach acid', 'Administering IV medication', 'A'),
  ('medical', 'gastrointestinal', '“Cirrhosis” refers to:', 'Inflammation of the pancreas', 'Stomach ulcer', 'Scarring of the liver', 'Intestinal blockage', 'C'),
  ('medical', 'gastrointestinal', '“Bowel prep” before a colonoscopy means:', 'Patient fasts completely', 'Cleaning out the intestines', 'Administering IV fluids', 'Taking antibiotics', 'B'),
  ('medical', 'gastrointestinal', '“Antiemetics” are medications that:', 'Stop nausea and vomiting', 'Reduce stomach acid', 'Relieve constipation', 'Treat liver disease', 'A'),
  ('medical', 'gastrointestinal', 'Which organ produces bile?', 'Pancreas', 'Liver', 'Stomach', 'Small intestine', 'B'),
  ('medical', 'gastrointestinal', '“Crohn’s disease” is a type of:', 'Liver disease', 'Inflammatory bowel disease', 'Stomach ulcer', 'Pancreatic disorder', 'B'),
  ('medical', 'gastrointestinal', 'Which of the following symptoms is considered an emergency in GI conditions?', 'Severe abdominal pain with vomiting blood', 'Mild bloating', 'Occasional diarrhea', 'Constipation', 'A'),
  ('medical', 'gastrointestinal', 'Which imaging test is most commonly used to detect gallstones?', 'Ultrasound', 'CT scan', 'MRI', 'ECG', 'A'),
  ('medical', 'gastrointestinal', '“Lithotripsy” is a procedure to:', 'Remove liver cysts', 'Break stones into smaller pieces', 'Place a stent', 'Treat ulcers', 'B'),
  ('medical', 'gastrointestinal', '“Steatorrhea” refers to:', 'Fatty stools', 'Bloody stools', 'Diarrhea', 'Vomiting', 'A'),
  ('medical', 'gastrointestinal', 'Hematemesis refers to:', 'Blood in stool', 'Blood in vomit', 'Yellow skin', 'Abdominal swelling', 'B'),
  ('medical', 'gastrointestinal', '“Probiotics” are used to:', 'Treat liver disease', 'Reduce stomach acid', 'Treat constipation only', 'Restore healthy gut bacteria', 'D'),
  ('medical', 'endocrinology', '“Hyperglycemia” refers to:', 'Low blood sugar', 'High blood sugar', 'Low hormone levels', 'High cholesterol', 'B'),
  ('medical', 'endocrinology', '“Insulin” is a hormone that:', 'Raises blood sugar', 'Lowers blood sugar', 'Controls blood pressure', 'Regulates calcium', 'B'),
  ('medical', 'endocrinology', '“Thyroid gland” is located in the:', 'Neck', 'Chest', 'Abdomen', 'Brain', 'A'),
  ('medical', 'endocrinology', '“Hypothyroidism” means:', 'Overactive thyroid', 'Underactive thyroid', 'Thyroid infection', 'Thyroid cancer', 'B'),
  ('medical', 'endocrinology', '“A1C test” measures:', 'Daily blood sugar', 'Insulin levels only', 'Average blood sugar over time', 'Kidney function', 'C'),
  ('medical', 'endocrinology', '“Metformin” is primarily used to:', 'Lower blood glucose', 'Treat hypothyroidism', 'Increase insulin resistance', 'Treat adrenal disorders', 'A'),
  ('medical', 'endocrinology', '“Retinopathy” in diabetes affects the:', 'Kidneys', 'Eyes', 'Nerves', 'Heart', 'B'),
  ('medical', 'endocrinology', '“TSH” is a lab test used to evaluate:', 'Pancreatic function', 'Kidney function', 'Liver enzymes', 'Thyroid function', 'D'),
  ('medical', 'endocrinology', '“Adrenal insufficiency” means:', 'Excess cortisol', 'Inadequate cortisol production', 'High insulin', 'Low thyroid hormone', 'B'),
  ('medical', 'endocrinology', '“Acromegaly” is caused by excess:', 'Cortisol', 'Insulin', 'Growth hormone', 'Thyroid hormone', 'C'),
  ('medical', 'endocrinology', '“Prolactinoma” is a tumor of the:', 'Adrenal gland', 'Pituitary gland', 'Thyroid gland', 'Pancreas', 'B'),
  ('medical', 'endocrinology', '“Graves’ ophthalmopathy” affects the:', 'Eyes', 'Kidneys', 'Lungs', 'Liver', 'A'),
  ('medical', 'endocrinology', '“Thyroidectomy” is:', 'Removal of the thyroid gland', 'Removal of adrenal glands', 'Biopsy of pancreas', 'Removal of pituitary', 'A'),
  ('medical', 'endocrinology', '“Moon face” and “central obesity” are signs of:', 'Addison’s disease', 'Cushing’s syndrome', 'Hyperthyroidism', 'Hypoglycemia', 'B'),
  ('medical', 'endocrinology', 'Which hormone is produced by the adrenal cortex and helps in stress response?', 'Cortisol', 'Epinephrine', 'Insulin', 'Thyroxine', 'A'),
  ('medical', 'endocrinology', '“Hyperkalemia” means:', 'Low potassium', 'High potassium', 'Low sodium', 'High calcium', 'B'),
  ('medical', 'endocrinology', '“Glycosuria” refers to:', 'Sugar in urine', 'Protein in urine', 'Blood in urine', 'Ketones in urine', 'A'),
  ('medical', 'endocrinology', 'Which endocrine gland is located above the kidneys?', 'Pituitary', 'Thyroid', 'Adrenal', 'Pancreas', 'C'),
  ('medical', 'endocrinology', 'A patient with polyuria, polydipsia, and weight loss likely has:', 'Diabetes mellitus', 'Hypothyroidism', 'Addison’s disease', 'Cushing’s syndrome', 'A'),
  ('medical', 'endocrinology', '“ACTH” is a hormone produced by the:', 'Thyroid', 'Adrenal gland', 'Pancreas', 'Pituitary gland', 'D'),
  ('medical', 'endocrinology', '“Radioactive iodine therapy” is used to treat:', 'Hypothyroidism', 'Hyperthyroidism', 'Diabetes', 'Adrenal insufficiency', 'B'),
  ('medical', 'endocrinology', 'The term “fasting blood glucose” means:', 'Blood sugar after eating', 'Blood sugar after exercise', 'Blood sugar after not eating for several hours', 'Random blood sugar', 'C'),
  ('medical', 'endocrinology', 'A doctor who specializes in diagnosing and treating hormonal disorders is called a:', 'Cardiologist', 'Endocrinologist', 'Pulmonologist', 'Gastroenterologist', 'B'),
  ('medical', 'endocrinology', '“Polyuria” refers to:', 'Frequent urination', 'Painful urination', 'Blood in urine', 'Low urine output', 'A'),
  ('medical', 'endocrinology', 'A patient with “weight gain, fatigue, and cold intolerance” may have:', 'Hyperthyroidism', 'Hypothyroidism', 'Diabetes', 'Hypertension', 'B'),
  ('medical', 'renal', '“Hematuria” refers to:', 'Blood in urine', 'Painful urination', 'Excess urine', 'Cloudy urine', 'A'),
  ('medical', 'renal', '“Pyelonephritis” is: Inflammation of bladder Infection of kidney ✔ Kidney stones Urethral obstruction . A patient who “wakes up multiple times at night to urinate” has:', 'Polyuria', 'Nocturia', 'Dysuria', 'Retention', 'B'),
  ('medical', 'renal', 'Which procedure is used to remove excess fluid and waste in kidney failure?', 'Catheterization', 'Ultrasound', 'Cystoscopy', 'Dialysis', 'D'),
  ('medical', 'renal', '“Hydronephrosis” refers to:', 'Swelling of the kidneys due to urine buildup', 'Infection of the bladder', 'Kidney stones', 'Urethral obstruction', 'A'),
  ('medical', 'renal', 'Which test detects urinary tract infections?', 'ECG', 'Chest X-ray', 'Urine culture', 'Blood glucose', 'C'),
  ('medical', 'renal', '“Uremia” refers to:', 'Excess potassium in blood', 'Accumulation of waste in blood', 'Low sodium', 'High glucose', 'B'),
  ('medical', 'renal', 'Which imaging test is commonly used to detect kidney stones?', 'Ultrasound', 'MRI', 'CT angiogram', 'ECG', 'A'),
  ('medical', 'renal', '“UTI” stands for:', 'Ureteral tissue inflammation', 'Urinary toxin imbalance', 'Urinary tract infection', 'Urethral tract injury', 'C'),
  ('medical', 'renal', 'A patient who “cannot empty their bladder” may have:', 'Incontinence', 'Urinary retention', 'Polyuria', 'Hematuria', 'B'),
  ('medical', 'renal', '“Foley catheter” is used to:', 'Measure blood pressure', 'Deliver oxygen', 'Drain urine from the bladder', 'Remove kidney stones', 'C'),
  ('medical', 'renal', '“Cystoscopy” is a procedure to:', 'Examine the bladder', 'Remove the kidney', 'Measure urine output', 'Treat infection', 'A'),
  ('medical', 'renal', 'Which specialist treats urinary system disorders?', 'Nephrologist', 'Urologist', 'Endocrinologist', 'Pulmonologist', 'B'),
  ('medical', 'renal', 'BPH (benign prostatic hyperplasia)” refers to:', 'Prostate cancer', 'Enlarged prostate', 'Kidney infection', 'Bladder stones', 'B'),
  ('medical', 'renal', 'Lithotripsy” in urology is used to:', 'Remove the bladder', 'Treat infection', 'Insert a catheter', 'Break kidney stones', 'D'),
  ('medical', 'renal', 'A patient with “loss of bladder control” is experiencing:', 'Urinary retention', 'Incontinence', 'Dysuria', 'Hematuria', 'B'),
  ('medical', 'renal', 'Oliguria” refers to:', 'Reduced urine output', 'Excessive urination', 'Painful urination', 'Night urination', 'A'),
  ('medical', 'renal', '“Creatinine” is a lab test used to assess:', 'Liver function', 'Kidney function', 'Heart enzymes', 'Blood sugar', 'B'),
  ('medical', 'renal', '“Diuretics” are medications that:', 'Reduce urine production', 'Increase urine production', 'Treat infection', 'Dissolve stones', 'B'),
  ('medical', 'renal', '“Cystitis” refers to:', 'Kidney infection', 'Bladder inflammation', 'Prostate enlargement', 'Ureter blockage', 'B'),
  ('medical', 'renal', 'Anuria” means:', 'No urine output', 'Low urine output', 'Painful urination', 'Blood in urine', 'A'),
  ('medical', 'renal', 'Which condition can cause “foamy urine” due to high protein content?', 'Nephrotic syndrome', 'Kidney stones', 'Pyelonephritis', 'Urethritis', 'A'),
  ('medical', 'renal', '“Dysuria” refers to:', 'Excess urine', 'Blood in urine', 'Painful urination', 'Incomplete emptying', 'C'),
  ('medical', 'renal', 'PSA test” is used to:', 'Measure kidney function', 'Screen prostate conditions', 'Detect bladder infection', 'Measure urine output', 'B'),
  ('medical', 'renal', '“Urine culture” is performed to:', 'Measure kidney size', 'Identify bacteria causing infection', 'Check blood sugar', 'Detect stones only', 'B'),
  ('medical', 'ob_gyn', 'A procedure that involves collecting cells from your cervix to test for cervical cancer in women.', 'Pap smear', 'CBC', 'Hysteroscopy', 'Otoscopy', 'A'),
  ('medical', 'ob_gyn', 'Disease  that is most often -- but not exclusively -- spread by sexual intercourse', 'STD', 'GAD', 'PPI', 'IBS', 'A'),
  ('medical', 'ob_gyn', 'A condition where tissue similar to the lining of the womb starts to grow in other places, such as the ovaries and fallopian tubes', 'Uterine fibroids', 'Menopause', 'Endometriosis', 'Uterine polyps', 'C'),
  ('medical', 'ob_gyn', 'A condition in which the ovaries produce an abnormal amount of androgen producing numerous small cysts (fluid-filled sacs) that form in the ovaries', 'GAD', 'PCOS', 'GERD', 'PTSD', 'B'),
  ('medical', 'ob_gyn', 'Condition when a fertilized egg implants itself outside of the womb, usually in one of the fallopian tubes:', 'Placenta previa', 'Ectopic pregnancy', 'Pre-eclampsia', 'Miscarriage', 'B'),
  ('medical', 'ob_gyn', 'All the following are types of STDs except:', 'Chlamydia', 'Gonorrhea', 'Eclampsia', 'Syphilis', 'C'),
  ('medical', 'ob_gyn', 'The time in a woman''s life when her period stops; usually occurs naturally after age 45', 'Early menarche', 'Menopause', 'Dysmenorrhea', 'Menorrhagia', 'B'),
  ('medical', 'ob_gyn', 'High blood sugar (glucose) that develops during pregnancy and usually disappears after giving birth.', 'Insulin resistant diabetes', 'Diabetes type 2', 'Gestational diabetes', 'Pregnancy toxicity', 'C'),
  ('medical', 'ob_gyn', 'Condition when your uterus can sag out of position', 'Uterine fibroids', 'Uterine cancer', 'Uterine prolapse', 'Uterine hyperplasia', 'C'),
  ('medical', 'ob_gyn', 'Surgical procedure by which one or more babies are delivered through an incision in the mother''s abdomen', 'Vaginal birth', 'Hysterectomy', 'Cesarean section', 'Assisted birth', 'C'),
  ('medical', 'ob_gyn', 'Making a cut in the area between the vagina and anus  during childbirth is called:', 'Tracheotomy', 'Episiotomy', 'Hysterectomy', 'Lobectomy', 'B'),
  ('medical', 'ob_gyn', 'A surgical procedure in which the cervix is opened, and a thin instrument is inserted into the uterus. This instrument is used to remove tissue from the inside of the uterus', 'Tubal ligation', 'Pap smear', 'Colposcopy', 'Dilation and curettage', 'D'),
  ('medical', 'ob_gyn', 'Exercises made to strengthen the pelvic floor muscles are called:', 'Heimlich maneuver', 'Braxton hicks', 'Cardio exercise', 'Kegel’s exercise', 'D'),
  ('medical', 'ob_gyn', 'Which hormone triggers ovulation?', 'FSH', 'LH', 'Estrogen', 'Progesterone', 'B'),
  ('medical', 'ob_gyn', 'Which imaging test is first-line for evaluating ovarian cysts?', 'Ultrasound', 'MRI', 'CT scan', 'X-ray', 'A'),
  ('medical', 'ob_gyn', 'Which condition involves non-cancerous growths in the uterus?', 'Fibroids', 'Endometriosis', 'Ovarian cysts', 'PID', 'A'),
  ('medical', 'ob_gyn', 'Which procedure removes the uterus?', 'Hysterectomy', 'Oophorectomy', 'Salpingectomy', 'Dilation & curettage', 'A'),
  ('medical', 'ob_gyn', 'Which pregnancy complication involves high blood pressure and organ damage?', 'Ectopic pregnancy', 'Preeclampsia', 'Gestational diabetes', 'Placenta previa', 'B'),
  ('medical', 'ob_gyn', 'A procedure in which a small amount of amniotic fluid is removed from around the fetus to test for genetic disorders, infections, or fetal lung maturity is called:', 'Ultrasound', 'Chorionic villus sampling (CVS)', 'Amniocentesis', 'Non-stress test', 'C'),
  ('medical', 'ob_gyn', 'Which hormone is primarily responsible for maintaining pregnancy?', 'Progesterone', 'Estrogen', 'LH', 'FSH', 'A'),
  ('medical', 'ob_gyn', 'Which test measures fetal heart rate and contractions?', 'Ultrasound', 'Non-stress test (NST)', 'Pap smear', 'Amniocentesis', 'B'),
  ('medical', 'ob_gyn', '“Polyhydramnios” means:', 'Excess amniotic fluid', 'Low amniotic fluid', 'Premature rupture of membranes', 'Placental abruption', 'A'),
  ('medical', 'ob_gyn', 'Which hormone stimulates milk production after birth? Oxytocin Prolactin ✔ Estrogen Progesterone 24, A patient presents with sudden abdominal pain and vaginal bleeding in late pregnancy. Most likely diagnosis:', 'Placental abruption', 'Ectopic pregnancy', 'Fibroids', 'PID', 'A'),
  ('medical', 'ob_gyn', 'A test that uses X-rays to examine breast tissue for early detection of cancer or other abnormalities is called:', 'Ultrasound', 'Mammogram', 'MRI', 'Pap smear', 'B'),
  ('medical', 'oncology', 'Neoplasm” refers to:', 'Infection', 'Inflammation', 'New and abnormal growth of tissue', 'Cyst', 'C'),
  ('medical', 'oncology', 'Which imaging test is commonly used for breast cancer screening?', 'Mammography', 'MRI', 'CT scan', 'Ultrasound', 'A'),
  ('medical', 'oncology', '“Metastasis” means:', 'Initial tumor growth', 'Spread of cancer from one site to another', 'Benign tumor', 'Infection', 'B'),
  ('medical', 'oncology', '“Biopsy” is:', 'Surgical removal of tissue for examination', 'Radiation therapy', 'Chemotherapy', 'Blood test', 'A'),
  ('medical', 'oncology', '“Hematologic malignancy” refers to:', 'Skin cancer', 'Bone cancer', 'Blood cancers', 'Brain tumor', 'C'),
  ('medical', 'oncology', 'Which tumor marker is associated with prostate cancer?', 'PSA', 'CEA', 'CA-125', 'AFP', 'A'),
  ('medical', 'oncology', '“Remission” in cancer means:', 'Cancer is worse', 'Symptoms reduced or gone', 'Cancer is cured', 'Cancer spread', 'B'),
  ('medical', 'oncology', '“Palliative care” aims to:', 'Improve quality of life, relieve symptoms', 'Cure cancer', 'Prevent cancer', 'Diagnose cancer', 'A'),
  ('medical', 'oncology', '“Cachexia” in cancer patients means:', 'Nausea only', 'Fatigue', 'Pain', 'Severe weight loss and muscle wasting', 'D'),
  ('medical', 'oncology', 'The word “benign” means:', 'Aggressive cancer', 'Non-cancerous growth', 'Metastatic disease', 'Infectious tumor', 'B'),
  ('medical', 'oncology', 'Adjuvant therapy” refers to:', 'First-line emergency treatment', 'Alternative medicine', 'Treatment after primary therapy to reduce recurrence', 'Diagnostic procedure', 'C'),
  ('medical', 'oncology', 'What is “chemotherapy”?', 'Radiation treatment', 'Surgical technique', 'Diagnostic imaging', 'Drug treatment to kill cancer cells', 'D'),
  ('medical', 'oncology', '“Radiation therapy” uses:', 'Antibiotics', 'High-energy rays', 'Hormones only', 'Physical therapy', 'B'),
  ('medical', 'oncology', 'The term “oncologist” refers to: A.. Cancer specialist physician ✔ B. Radiologist C. Surgeon only D. Pathologist 14,“Leukemia” affects primarily:', 'Skin', 'Blood and bone marrow', 'Lungs', 'Liver', 'B'),
  ('medical', 'oncology', 'What does “prognosis” refer to?', 'Diagnosis of disease', '. Treatment plan', 'Expected outcome or course of disease', 'Lab result', 'C'),
  ('medical', 'oncology', 'Recurrence” means:', 'Initial diagnosis', 'Cancer returning after treatment', 'Complete cure', 'Side effect of drugs', 'B'),
  ('medical', 'oncology', 'partial or complete removal of a limb is :', 'None of the above', 'None of the above', 'None of the above', 'None of the above', 'A'),
  ('medical', 'oncology', 'Amputation ✔', 'None of the above', 'None of the above', 'None of the above', 'None of the above', 'A'),
  ('medical', 'oncology', 'Hip replacement', 'None of the above', 'None of the above', 'None of the above', 'None of the above', 'A'),
  ('medical', 'oncology', 'Chiropractor', 'None of the above', 'None of the above', 'None of the above', 'None of the above', 'A'),
  ('medical', 'oncology', 'internal fixation', 'None of the above', 'None of the above', 'None of the above', 'None of the above', 'A'),
  ('medical', 'oncology', 'A rapidly enlarging neck mass could suggest:', 'Thyroid cancer', 'Tonsillitis only', 'Skin allergy', 'None of the above', 'A'),
  ('medical', 'oncology', 'Simple dehydration', 'None of the above', 'None of the above', 'None of the above', 'None of the above', 'A'),
  ('medical', 'oncology', '“Carcinoma” originates from:', 'Connective tissue', 'Bone', 'Epithelial cells', 'Nerve cells', 'C'),
  ('medical', 'oncology', 'Which symptom is common in colorectal cancer?', 'Blood in stool', 'Rash', 'Fever', 'Shortness of breath', 'A'),
  ('medical', 'dermatology', '“Psoriasis” is characterized by:', 'Red, scaly patches on the skin', 'Fluid-filled blisters', 'Pustules with pus', 'Skin necrosis', 'A'),
  ('medical', 'dermatology', '“Urticaria” is also known as:', 'Psoriasis', 'Hives', 'Eczema', 'Rosacea', 'B'),
  ('medical', 'dermatology', 'Vitiligo” is a condition of:', 'Hair loss', 'Red rash', 'Skin depigmentation', 'Blistering', 'C'),
  ('medical', 'dermatology', 'Hair loss that can affect just your scalp or your entire body, and it can be temporary or permanent', 'Vitiligo', 'Lupus', 'Alopecia', 'Acne', 'C'),
  ('medical', 'dermatology', 'A  thickened, hardened area of skin that develops due to repeated friction, pressure, or irritation.', 'Callus', 'Moles', 'Vitiligo', 'Warts', 'A'),
  ('medical', 'dermatology', 'A painful, pus-filled bump that forms under your skin when bacteria infect and inflame one or more of your hair follicles', 'Rash', 'Eczema', 'Boil', 'Hives', 'C'),
  ('medical', 'dermatology', 'What is cauterization?', 'Surgical removal', 'Burning of part of a body to remove or close off a part of it', 'Application of extreme cold to freeze and destroy abnormal tissue', 'Grafting', 'B'),
  ('medical', 'dermatology', 'A localized collection of pus that forms due to infection..', 'Abscess', 'Callus', 'Inflammation of the skin', 'Scar', 'A'),
  ('medical', 'dermatology', 'A  medical doctor who specializes in diagnosing and treating conditions of the skin, hair, and nails.', 'Neurologist', 'Cardiologist', 'Dermatologist', 'Podiatrist', 'C'),
  ('medical', 'dermatology', 'Shingles is caused by:', 'Herpes simplex', 'Varicella zoster', 'HPV', 'Gonorrhea', 'B'),
  ('medical', 'dermatology', 'What is eczema?', 'Bacterial skin infection', 'Chronic inflammation of the skin', 'Skin cancer', 'Viral disease', 'B'),
  ('medical', 'dermatology', 'Fluid-filled pocket on the skin refers to:', 'Solid lump', 'Dry patch', 'Blister', 'Scar tissue', 'C'),
  ('medical', 'dermatology', 'A genetic condition with little or no pigment in skin, hair, and eyes refers to:', 'Skin infection', 'Albinism', 'Cancer', 'Allergy', 'B'),
  ('medical', 'dermatology', 'What is a mole (nevus)? A. Malignant tumor B. Benign growth of pigmented skin cells ✔ C. Infection D. Rash Answer: B 15Application of extreme cold to freeze and destroy abnormal tissue refers to:', 'Surgical removal', 'Burning of part of a body to remove or close off a part of it', 'Cryotherapy', 'Grafting', 'C'),
  ('medical', 'dermatology', 'Contact dermatitis” is triggered by:', 'Allergens or irritants', 'Bacteria', 'Hormones', 'Genetics', 'A'),
  ('medical', 'dermatology', '“Biopsy” in dermatology is used to:', 'Treat skin infection', 'Remove warts', 'Diagnose skin lesions', 'Reduce inflammation', 'C'),
  ('medical', 'dermatology', 'Rosacea” typically affects:', 'Scalp', 'Face', 'Hands', 'Feet', 'B'),
  ('medical', 'dermatology', 'A contagious skin infection characterized by red, ring-shaped rash refers to:', 'Psoriasis', 'Ringworm', 'Albinism', 'Urticaria', 'B'),
  ('medical', 'dermatology', '“Hyperpigmentation” refers to:', 'Loss of skin color', 'Darkening of the skin', 'Redness', 'Blistering', 'B'),
  ('medical', 'dermatology', '“Hypopigmentation” refers to:', 'Light patches on the skin', 'Dark spots', 'Rash with pus', 'Red scaly patches', 'A'),
  ('medical', 'dermatology', 'A patient has itchy, red, raised wheals after eating seafood. This is most likely:', 'Eczema', 'Urticaria', 'Psoriasis', 'Rosacea', 'B'),
  ('medical', 'dermatology', 'Topical corticosteroids” are mainly used to:', 'Kill bacteria', 'Reduce inflammation', 'Treat fungal infections', 'Stimulate hair growth', 'B'),
  ('medical', 'dermatology', 'A patient presents with blistering on lips and mouth after stress. Likely diagnosis:', 'Cold sores', 'Canker sores', 'Impetigo', 'Eczema', 'A'),
  ('medical', 'dermatology', 'Red, inflamed skin caused by overexposure to the sun refers to:', 'Acne', 'Sunburn', 'Eczema', 'Infection', 'B'),
  ('medical', 'emergency', 'A patient arrives with sudden chest pain radiating to the left arm. Likely diagnosis:', 'Myocardial infarction', 'Asthma', 'Stroke', 'Pneumonia', 'A'),
  ('medical', 'emergency', '“Dyspnea” means:', 'Chest pain', 'Shortness of breath', 'Dizziness', 'Cough', 'B'),
  ('medical', 'emergency', 'A patient presents with a severe allergic reaction, swelling of face and throat. Immediate action:', 'Giving epinephrine', 'Give acetaminophen', 'Apply ice', 'Start IV fluids', 'A'),
  ('medical', 'emergency', 'Hemorrhage” refers to:', 'Infection', 'Swelling', 'Fracture', 'Excessive bleeding', 'D'),
  ('medical', 'emergency', 'Tachycardia” means:', 'Fast heart rate', 'Slow heart rate', 'Chest pain', 'Shortness of breath', 'A'),
  ('medical', 'emergency', 'Sepsis” is defined as:', 'Heart attack', 'Stroke', 'Life-threatening organ dysfunction due to infection', 'Asthma', 'C'),
  ('medical', 'emergency', 'Hypoxia” means:', 'Low oxygen in the blood', 'High blood pressure', 'Low heart rate', 'Fever', 'A'),
  ('medical', 'emergency', 'Cardiac arrest” is:', 'Heart rate too fast', 'Heart stops beating effectively', 'Chest pain only', 'Shortness of breath', 'B'),
  ('medical', 'emergency', 'Hypovolemic shock” results from:', 'Severe blood or fluid loss', 'Heart failure', 'Infection', 'Allergic reaction', 'A'),
  ('medical', 'emergency', 'CPR” stands for:', 'Cardiac Pulmonary Resuscitation', 'Cardiopulmonary Resuscitation', 'Central Pulse Response', 'Critical Patient Rescue', 'B'),
  ('medical', 'emergency', 'Anaphylaxis” is:', 'Mild allergic reaction', 'Heart attack', 'Seizure', 'Severe, potentially life-threatening allergic reaction', 'D'),
  ('medical', 'emergency', '“Tachypnea” means:', 'Slow breathing', 'Fast breathing', 'Irregular heartbeat', 'Low blood pressure', 'B'),
  ('medical', 'emergency', 'Asthma attack” emergency treatment includes:', 'Inhaled bronchodilator', 'Antibiotics', 'Surgery', 'Insulin', 'A'),
  ('medical', 'emergency', 'Syncope” is:', 'Fainting', 'Seizure', 'Stroke', 'Heart attack', 'A'),
  ('medical', 'emergency', 'In emergency interpreting, the MOST important principle is:', 'Paraphrasing freely', 'Adding explanations from your own knowledge', 'Accuracy and completeness', 'Shortening the message', 'C'),
  ('medical', 'emergency', 'Bluish discoloration of lips or skin due to lack of oxygen refers to:', 'Redness', 'Cyanosis', 'Rash', 'Burn', 'B'),
  ('medical', 'emergency', 'Persistent vomiting and inability to keep fluids refers to:', 'Hunger', 'Dehydration', 'Allergy', 'Fatigue', 'B'),
  ('medical', 'emergency', 'Involuntary shaking or convulsions refers to:', 'Tremor', 'Seizure', 'Fatigue', 'Paralysis', 'B'),
  ('medical', 'emergency', 'Complete inability to move a part of the body refers to:', 'Weakness', 'Pain', 'Swelling', 'Paralysis', 'D'),
  ('medical', 'emergency', 'Sudden severe headache (worst ever) refers to:', 'Tension headache', 'Subarachnoid Hemorrhage', 'Migraine', 'Sinusitis', 'B'),
  ('medical', 'ear_and_eye', 'Sudden loss of vision in one eye refers to:', 'Conjunctivitis', 'Retinal Detachment', 'Dry eye', 'Headache', 'B'),
  ('medical', 'ear_and_eye', 'Red eye with itching and discharge is most likely:', 'Glaucoma', 'Conjunctivitis', 'Cataract', 'Migraine', 'B'),
  ('medical', 'ear_and_eye', 'A condition where the optic nerve is damaged due to high intraocular pressure is:', 'Cataract', 'Glaucoma', 'Conjunctivitis', 'Strabismus', 'B'),
  ('medical', 'ear_and_eye', 'Gradual loss of vision with cloudy lens refers to:', 'Conjunctivitis', 'Cataract', 'Retinal detachment', 'Stroke', 'B'),
  ('medical', 'ear_and_eye', 'Foreign body sensation in the eye most likely indicates:', 'Migraine', 'Cataract', 'Glaucoma', 'Corneal Abrasion', 'D'),
  ('medical', 'ear_and_eye', 'Sudden ear pain with fever suggests:', 'Allergy', 'Otitis Media', 'Tinnitus', 'Dry eye', 'B'),
  ('medical', 'ear_and_eye', 'Ringing in the ear without external sound is:', '. Tinnitus', 'Vertigo', '. Infection', 'Headache', 'A'),
  ('medical', 'ear_and_eye', 'Spinning sensation and imbalance indicates:', 'Migraine', 'Vertigo', 'Fever', 'Rash', 'B'),
  ('medical', 'ear_and_eye', 'Ear discharge with pain usually indicates:', 'Allergy', 'Otitis Externa', 'Stroke', 'Diabetes', 'B'),
  ('medical', 'ear_and_eye', 'Surgical repair of the small bones in the middle ear to improve hearing is:', 'Myringoplasty', 'Ossiculoplasty', 'Cochlear implant', 'Ophthalmoscopy', 'B'),
  ('medical', 'ear_and_eye', 'Eye pain with redness and sensitivity to light may indicate:', 'Conjunctivitis', 'Cataract', 'Uveitis', '. Dry eye', 'C'),
  ('medical', 'ear_and_eye', 'Excessive tearing and itchy eyes suggest:', 'Glaucoma', 'Allergic Conjunctivitis', 'Stroke', 'Cataract', 'B'),
  ('medical', 'ear_and_eye', 'Surgical removal of the cloudy lens in the eye and replacement with an artificial lens is called:', 'Cataract Surgery', 'Strabismus correction', 'Tympanoplasty', 'Vitrectomy', 'A'),
  ('medical', 'ear_and_eye', 'A test used to measure hearing ability using sound tones at different frequencies is:', 'Otoscopy', 'Audiometry', 'Fundoscopy', 'Tympanoplasty', 'B'),
  ('medical', 'ear_and_eye', 'Blurred vision with headache may indicate:', 'Allergy', 'Migraine', 'Infection', 'Earwax', 'B'),
  ('medical', 'ear_and_eye', 'Feeling of pressure in the ear is often due to:', 'Eustachian Tube Dysfunction', 'Stroke', 'Cataract', 'Rash', 'A'),
  ('medical', 'ear_and_eye', 'Diagnostic procedure that employs the use of mydriatic eye drops  to dilate or enlarge the pupil in order to obtain a better view of the fundus of the eye', 'Angiopathy', 'Otoscopy', 'Fundus examination', 'EEG', 'C'),
  ('medical', 'ear_and_eye', 'Painful swelling of eyelid is:', 'Cataract', 'Stye', 'Glaucoma', 'Migraine', 'B'),
  ('medical', 'ear_and_eye', 'Specialist who treats eye diseases and perform eye surgeries :', 'Optometrist', 'Ophthalmologist', 'Pulmonologist', 'Neurologist', 'B'),
  ('medical', 'ear_and_eye', 'Sudden dizziness with hearing changes suggests:', 'Stroke', 'Meniere Disease', 'Rash', 'Fever', 'B'),
  ('medical', 'ear_and_eye', 'What is the medical term for crossed eyes?', 'Strabismus', 'Cataract', 'Glaucoma', 'Cauterization', 'A'),
  ('medical', 'ear_and_eye', 'A medical condition which may result in blurred or no vision in the center of the visual field', 'Macular degeneration', 'Strabismus', 'Retinal detachment', 'Sty', 'A'),
  ('medical', 'ear_and_eye', 'Condition in which you can see objects near to you clearly, but objects farther away are blurry:', 'Hypermetropia', 'Myopia', 'Cataract', 'Blurry vision', 'B'),
  ('medical', 'ear_and_eye', 'Define myringoplasty?', 'Surgical repair of an aneurysm', 'Surgical repair of blood vessels', 'Surgical repair of heart valve', 'Surgical repair of eardrum', 'D'),
  ('medical', 'ear_and_eye', 'What is a cochlear implant?', 'A battery-powered electronic device designed to improve your hearing', 'A small electronic device that electrically stimulates the auditory nerve for hearing', 'Device used to maintain the rhythm of the heart', 'Device used for visual examination of the ear', 'B');
