-- Create languages table
CREATE TABLE IF NOT EXISTS public.languages (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

-- Insert all languages (122 languages)
INSERT INTO public.languages (id, name) VALUES
(1, 'Afrikaans'),
(2, 'Albanian'),
(3, 'Amharic'),
(4, 'Arabic'),
(5, 'Egyptian Arabic'),
(6, 'Moroccan Arabic'),
(7, 'Levantine Arabic'),
(8, 'Gulf Arabic'),
(9, 'Tunisian Arabic'),
(10, 'Sudanese Arabic'),
(11, 'Iraqi Arabic'),
(12, 'Algerian Arabic'),
(13, 'Armenian'),
(14, 'Assamese'),
(15, 'Azerbaijani'),
(16, 'Basque'),
(17, 'Belarusian'),
(18, 'Bengali'),
(19, 'Bosnian'),
(20, 'Bulgarian'),
(21, 'Burmese'),
(22, 'Catalan'),
(23, 'Cebuano'),
(24, 'Chichewa'),
(25, 'Chinese (Simplified)'),
(26, 'Chinese (Traditional)'),
(27, 'Corsican'),
(28, 'Croatian'),
(29, 'Czech'),
(30, 'Danish'),
(31, 'Dutch'),
(32, 'English'),
(33, 'Esperanto'),
(34, 'Estonian'),
(35, 'Farsi'),
(36, 'Filipino'),
(37, 'Finnish'),
(38, 'French'),
(39, 'Frisian'),
(40, 'Galician'),
(41, 'Georgian'),
(42, 'German'),
(43, 'Greek'),
(44, 'Gujarati'),
(45, 'Haitian Creole'),
(46, 'Hausa'),
(47, 'Hawaiian'),
(48, 'Hebrew'),
(49, 'Hindi'),
(50, 'Hmong'),
(51, 'Hungarian'),
(52, 'Icelandic'),
(53, 'Igbo'),
(54, 'Indonesian'),
(55, 'Irish'),
(56, 'Italian'),
(57, 'Japanese'),
(58, 'Javanese'),
(59, 'Kannada'),
(60, 'Kazakh'),
(61, 'Khmer'),
(62, 'Kinyarwanda'),
(63, 'Korean'),
(64, 'Kurdish (Kurmanji)'),
(65, 'Kyrgyz'),
(66, 'Lao'),
(67, 'Latin'),
(68, 'Latvian'),
(69, 'Lithuanian'),
(70, 'Luxembourgish'),
(71, 'Macedonian'),
(72, 'Malagasy'),
(73, 'Malay'),
(74, 'Malayalam'),
(75, 'Maltese'),
(76, 'Maori'),
(77, 'Marathi'),
(78, 'Mongolian'),
(79, 'Nepali'),
(80, 'Norwegian'),
(81, 'Nyanja'),
(82, 'Odia'),
(83, 'Pashto'),
(84, 'Persian'),
(85, 'Polish'),
(86, 'Portuguese'),
(87, 'Punjabi'),
(88, 'Romanian'),
(89, 'Russian'),
(90, 'Samoan'),
(91, 'Scots Gaelic'),
(92, 'Serbian'),
(93, 'Sesotho'),
(94, 'Shona'),
(95, 'Sindhi'),
(96, 'Sinhala'),
(97, 'Slovak'),
(98, 'Slovenian'),
(99, 'Somali'),
(100, 'Spanish'),
(101, 'Sundanese'),
(102, 'Swahili'),
(103, 'Swedish'),
(104, 'Tajik'),
(105, 'Tamil'),
(106, 'Tatar'),
(107, 'Telugu'),
(108, 'Thai'),
(109, 'Tigrinya'),
(110, 'Turkish'),
(111, 'Turkmen'),
(112, 'Ukrainian'),
(113, 'Urdu'),
(114, 'Uyghur'),
(115, 'Uzbek'),
(116, 'Vietnamese'),
(117, 'Welsh'),
(118, 'Western Frisian'),
(119, 'Xhosa'),
(120, 'Yiddish'),
(121, 'Yoruba'),
(122, 'Zulu')
ON CONFLICT (id) DO NOTHING;

-- Create index on name for faster lookups
CREATE INDEX IF NOT EXISTS idx_languages_name ON public.languages(name);

-- Enable Row Level Security
ALTER TABLE public.languages ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all authenticated users to read languages
CREATE POLICY "Anyone can view languages" ON public.languages
    FOR SELECT USING (true);

-- Grant permissions
GRANT SELECT ON public.languages TO authenticated;
GRANT SELECT ON public.languages TO anon;

